#!/usr/bin/env ruby

require 'rubygems'
require 's3_lib'

# Usage: download_object <bucket> <key> <file>
# Downloads the object with a key of key in the bucket named bucket and 
# writes it to a file named filename.
bucket, key, filename = ARGV
url = File.join(bucket, key)
contents = S3Lib.request(:get, url).read

File.open(filename, 'w') do |file|
  file.write(contents)
end