#!/usr/bin/env ruby

require 'digest'
require 'rubygems'
require 'aws/s3'
include AWS::S3

# Usage: detect_file_differences <local file name> <bucket> [<key>]
# key will default to filename if it is not given.

filename = ARGV[0]
bucket = ARGV[1]
key = ARGV[2] || filename

AWS::S3::Base.establish_connection!(
    :access_key_id     => ENV['AMAZON_ACCESS_KEY_ID'],
    :secret_access_key => ENV['AMAZON_SECRET_ACCESS_KEY']
)

begin
  object = S3Object.find(key, bucket)
rescue AWS::S3::NoSuchKey
  puts "The file does not exist on S3.  You need to upload"
  exit(0)
end

md5 = Digest::MD5.hexdigest(File.read(filename))
etag = object.etag

if md5 == etag
  puts "They're the same.  No need to upload"
else
  puts "They're different.  You need to upload the file to S3."
end